name: run

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed
  push:
    paths:
      - "**"
      - "!./.github/workflows/*"
      - "!build.py"

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 'Run Python'
        run: python3 ./main.py
      - name: 'Logging'
        run: |
          echo "Logging..."
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "MESSAGE: $MESSAGE"
