on:
  push:
    branches:
      - "workflows"
    paths:
      - "./sandbox/**/*.py"

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3
      - name: 'Setup Python'
        uses: action/setup-python@v3
        with:
          python-version: '3.10'
      - name: 'Run Python'
        run: python3 ./main.py
